# Generated by Django 5.1.2 on 2024-10-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cnic_encrypted',
        ),
        migrations.AddField(
            model_name='member',
            name='cnic',
            field=models.CharField(default=None, max_length=13, null=True),
        ),
    ]
