# Generated by Django 5.1.2 on 2024-10-09 02:27

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_member_cnic_encrypted_member_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='business_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='business_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='country_of_stay',
            field=django_countries.fields.CountryField(default='PK', max_length=2),
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(default='Member', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='dual_citizen',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='employee_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='nic_type',
            field=models.CharField(choices=[('cnic', 'CNIC'), ('nicop', 'NICOP')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='other_citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='permanent_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_pics/'),
        ),
        migrations.AddField(
            model_name='member',
            name='present_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='pri_land',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pri_mob',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='sec_land',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sec_mob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.district'),
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.district')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='tehsil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.tehsil'),
        ),
    ]
