# Generated by Django 5.1.2 on 2024-10-09 15:37

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_district_remove_member_address_remove_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='other_citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('annual', 'Annual'), ('registration', 'Registration')], max_length=50)),
                ('submission_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('cash', 'Cash')], max_length=50)),
                ('amount_submitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.member')),
            ],
        ),
    ]
