# Generated by Django 5.1.2 on 2024-10-10 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_member_cnic_alter_member_other_citizenship_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='renewal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
