# Generated by Django 5.1.2 on 2024-10-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_fee_renewal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_method', models.CharField(choices=[('cash', 'By Cash'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fee',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('new registration', 'New Registration'), ('renewal', 'Renewal'), ('change of information', 'Change of Information'), ('transfer of ownership', 'Transfer of Ownership'), ('transfer of ownership (DEATH OF ORIGINAL OWNER)', 'Transfer of Ownership (DEATH OF ORIGINAL OWNER)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fee',
            name='submission_method',
            field=models.CharField(choices=[('cash', 'By Cash'), ('bank_transfer', 'Bank Transfer')], max_length=50),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.payment'),
        ),
    ]
