# Generated by Django 5.1.2 on 2024-10-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_payment_remove_fee_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
