# Generated by Django 5.1.2 on 2024-10-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_member_is_approved_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
