# Generated by Django 5.1.2 on 2024-10-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_tehsil_latitude_tehsil_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
