# Generated by Django 5.1.2 on 2024-10-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_payment_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='branch_code',
        ),
    ]
