# Generated by Django 5.1.2 on 2024-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_memberchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dual_citizen',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default=False),
        ),
    ]
