# Generated by Django 5.1.2 on 2024-10-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_member_dual_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dual_citizen',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
    ]
