# Generated by Django 5.1.2 on 2024-10-17 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_member_dual_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
