# Generated by Django 5.1.2 on 2024-10-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_fee_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchangerequest',
            name='application_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
