# Generated by Django 5.1.2 on 2024-10-19 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_memberchangerequest_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchangerequest',
            name='fee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.fee'),
        ),
    ]
