# Generated by Django 5.1.2 on 2024-10-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_memberchangerequest_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='application_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
