# Generated by Django 5.1.2 on 2024-10-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_fee_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='application_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
