# Generated by Django 5.1.2 on 2024-10-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_fee_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.payment'),
        ),
    ]
