# Generated by Django 5.1.2 on 2024-10-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_fee_application_id_alter_fee_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member'),
        ),
    ]
