# Generated by Django 5.1.2 on 2024-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_fee_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberchangerequest',
            name='new_dual_citizen',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
    ]
