# Generated by Django 5.1.2 on 2024-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_user_currency_association_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_association_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
