# Generated by Django 5.1.2 on 2024-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_alter_user_currency_association_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='application_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
